services:
  go-dump-postgres:
    build: 
      context: .
      dockerfile: Dockerfile
    image: auroraphtgrp/go-dump-postgres:latest
    container_name: go-dump-postgres-app
    restart: always
    environment:
      - DOMAIN_HOST=dump.uniko.id.vn
    ports:
      - "8888:8080"
    volumes:
      - ./backups:/app/backups
      - ./backup:/app/backup
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
